Repository desmos-labs/primer, pull requests merged in 2020-01, with the labels that each got.

#22 level 1 - referred
  phases/phase-1/challenges/referred/creamjun
Labels: Status:Waiting user

#48 Challenge 1 - Friend Referral
  phases/phase-1/challenges/likes/rkyassine
  phases/phase-1/challenges/referral/rkyassine
Labels: Status:Waiting user

#50 Challenges description improvements
  .vuepress/config.js
  README.md
  package-lock.json
  phases/phase-1/README.md
  phases/phase-1/challenges/README.md
  phases/phase-1/challenges/accept-referral.md
  phases/phase-1/challenges/create-post.md
  phases/phase-1/challenges/level-1.md
  phases/phase-1/challenges/level-2.md
  phases/phase-1/challenges/like-post.md
  phases/phase-1/challenges/refer.md
  phases/phase-1/setup/README.md
Labels: documentation

#34 Phase 1 Level 1,2
  phases/phase-1/challenges/likes/Alive29
  phases/phase-1/challenges/posts/Alive29
  phases/phase-1/challenges/referral/Alive29
  phases/phase-1/challenges/referred/Alive29
Labels: Status:Waiting user

#38 Phase 1 challenges Level 1 & 2
  phases/phase-1/challenges/likes/Grom81
  phases/phase-1/challenges/posts/Grom81
  phases/phase-1/challenges/referral/Grom81
  phases/phase-1/challenges/referred/Grom81
Labels: Status:Waiting other PR

#56 referred
  phases/phase-1/challenges/likes/dafricash
  phases/phase-1/challenges/posts/dafricash
  phases/phase-1/challenges/referred/dafricash
Labels: Status:Waiting user

#60 Phase 2
  .gitignore
  .vuepress/config.js
  .vuepress/config_en.js
  .vuepress/config_ru.js
  .vuepress/public/assets/cover.jpg
  .vuepress/public/assets/logo.png
  .vuepress/public/assets/logo.svg
  .vuepress/public/assets/pwa/android-icon-144x144.png
  .vuepress/public/assets/pwa/android-icon-192x192.png
  .vuepress/public/assets/pwa/android-icon-36x36.png
  .vuepress/public/assets/pwa/android-icon-48x48.png
  .vuepress/public/assets/pwa/android-icon-72x72.png
  .vuepress/public/assets/pwa/android-icon-96x96.png
  .vuepress/public/assets/pwa/apple-icon-114x114.png
  .vuepress/public/assets/pwa/apple-icon-120x120.png
  .vuepress/public/assets/pwa/apple-icon-144x144.png
  .vuepress/public/assets/pwa/apple-icon-152x152.png
  .vuepress/public/assets/pwa/apple-icon-180x180.png
  .vuepress/public/assets/pwa/apple-icon-57x57.png
  .vuepress/public/assets/pwa/apple-icon-60x60.png
  .vuepress/public/assets/pwa/apple-icon-72x72.png
  .vuepress/public/assets/pwa/apple-icon-76x76.png
  .vuepress/public/assets/pwa/apple-icon-precomposed.png
  .vuepress/public/assets/pwa/apple-icon.png
  .vuepress/public/assets/pwa/browserconfig.xml
  .vuepress/public/assets/pwa/favicon-16x16.png
  .vuepress/public/assets/pwa/favicon-32x32.png
  .vuepress/public/assets/pwa/favicon-96x96.png
  .vuepress/public/assets/pwa/favicon.ico
  .vuepress/public/assets/pwa/manifest.json
  .vuepress/public/assets/pwa/ms-icon-144x144.png
  .vuepress/public/assets/pwa/ms-icon-150x150.png
  .vuepress/public/assets/pwa/ms-icon-310x310.png
  .vuepress/public/assets/pwa/ms-icon-70x70.png
  README.md
  phases/phase-1/README.md
  phases/phase-1/challenges/README.md
  phases/phase-1/challenges/accept-referral.md
  phases/phase-1/challenges/create-post.md
  phases/phase-1/challenges/like-post.md
  phases/phase-1/challenges/refer.md
  phases/phase-1/setup/README.md
  phases/phase-2/README.md
  phases/phase-2/challenges/add-reaction.md
  phases/phase-2/challenges/become-validator.md
  phases/phase-2/challenges/reactions/.gitkeep
  ru/phases/phase-1/README.md
  ru/phases/phase-1/challenges/README.md
  ru/phases/phase-1/challenges/accept-referral.md
  ru/phases/phase-1/challenges/create-post.md
  ru/phases/phase-1/challenges/like-post.md
  ru/phases/phase-1/challenges/refer.md
  ru/phases/phase-1/setup/README.md
Labels: documentation

#71 Accepted referral
  phases/phase-1/challenges/posts/PrathyushaLakkireddy
  phases/phase-1/challenges/referred/PrathyushaLakkireddy
Labels: Status:Waiting user

#89 accept
  phases/phase-1/challenges/likes/nelinam
  phases/phase-1/challenges/posts/nelinam
  phases/phase-1/challenges/referred/nelinam
Labels: Status:Waiting user

#91 Phase 1 & 2 - Challenges
  phases/phase-1/challenges/posts/Wanderer-Cry
  phases/phase-1/challenges/referred/Wanderer-Cry
Labels: Status:Waiting user

#102 Accepted referral
  phases/phase-1/challenges/likes/stakervali
  phases/phase-1/challenges/posts/stakervali
  phases/phase-1/challenges/referred/stakervali
Labels: Status:Waiting user

#101 defitrader challenge
  phases/phase-1/challenges/likes/defitrader
  phases/phase-1/challenges/posts/defitrader
  phases/phase-1/challenges/referral/defitrader
Labels: Status:Waiting user

#35 iammelea
  phases/phase-1/challenges/likes/iammelea
  phases/phase-1/challenges/posts/iammelea
  phases/phase-1/challenges/referral/iammelea
  phases/phase-1/challenges/referred/iammelea
Labels: Status:Waiting user

#62 Nazar phase 1 challenges
  phases/phase-1/challenges/posts/CNazar
  phases/phase-1/challenges/referral/CNazar
  phases/phase-1/challenges/referred/CNazar
Labels: Status:Waiting user

#67 Added referred username
  phases/phase-1/challenges/likes/sahith-narahari
  phases/phase-1/challenges/posts/sahith-narahari
  phases/phase-1/challenges/referred/sahith-narahari
Labels: Status:Waiting user

#74 referred by kaustubh
  phases/phase-1/challenges/posts/siva1933
  phases/phase-1/challenges/referred/siva1933
Labels: Status:Waiting user
